### ISSUE TITLE
Class 'Invoice' not found

### ISSUE THREAD

**Issue by krehak** [quickshiftin/php-pdf-invoice#4]
Well I'm new to composer and not using it a lot. But I can't get your code working:
```
use Quickshiftin\Pdf\Invoice as PdfInvoice;
use Quickshiftin\Pdf\Invoice\Factory as InvoiceFactory;

$oInvoiceFactory = new InvoiceFactory();
$oInvoicePdf     = new Invoice();
```

What to do?

**Comment by quickshiftin** [comment]
Did you
```php
require 'vendor/autoload.php';
```
?

**Comment by krehak** [comment]
Yes I did, because I also use other composer packages and they are all working good.

**Comment by quickshiftin** [comment]
Ok, what is the error messages you get?

**Comment by krehak** [comment]
I said it in the title "Class 'Invoice' not found". But "InvoiceFactory" is available.

**Comment by quickshiftin** [comment]
I see now, the `use` statement creates the `Quickshiftin\Pdf\Invoice` alias as **`PdfInvoice`**, so the second line should be `$oInvoicePdf = new PdfInvoice();`.

I've cleaned up the documentation, thanks for bringing this to my attention!

**Comment by krehak** [comment]
Yea I thought this should be it, but now I get error `Class 'Quickshiftin\Pdf\Invoice' not found` calling on line with `$oInvoicePdf = new PdfInvoice();`

**Comment by quickshiftin** [comment]
Looks like another typo in the documentation, the `use` statement should be
```php
use Quickshiftin\Pdf\Invoice\Invoice as PdfInvoice;
```
I've updated the documentation again as well.

**Comment by krehak** [comment]
Great now it's OK, thanks!
