### ISSUE TITLE
Setters to override default currency and strings

### ISSUE THREAD

**Issue by futurewebsites** [quickshiftin/php-pdf-invoice#5]
is it possible to override the currency and default strings? currently they are all hardcoded and or private properties

        $_sOrderText                  = 'Order # ',
        $_sOrderDateText              = 'Order Date: ',
        $_sOrderDateFormat            = 'M jS Y g:i a',
        $_sSoldToText                 = 'Sold to',
        $_sShipToText                 = 'Ship to',
        $_sPaymentMethodText          = 'Payment Method',
        $_sShippingMethodText         = 'Shipping Method',
        $_sProductColumnText          = 'Products',
        $_sSkuColumnText              = 'SKU',
        $_sPriceColumnText            = 'Price',
        $_sQtyColumnText              = 'Qty',
        $_sTaxColumnText              = 'Tax',
        $_sSubTotalColumnText         = 'Subtotal',
        $_sSubTotalText               = 'Subtotal',
        $_sShippingHandlingText       = 'Shipping & Handling',
        $_sGrandTotalExcludingTaxText = 'Grand Total (Excl. Tax)',
        $_sTaxText                    = 'Tax',
        $_sGrandTotalIncludingTaxText = 'Grand Total (Incl. Tax)',

**Comment by quickshiftin** [comment]
Hi, these should all be configurable via `ArrayAccess` interface. For example if you have an `Invoice` instance `$invoice`, you can change `$_sOrderText` like this
```
$invoice['OrderText'] = 'Order Number';
```
The others are all the same way, just drop the `_s` prefix for the key you use when setting. Have a look at [`Invoice::__offsetSet`](https://github.com/quickshiftin/php-pdf-invoice/blob/master/src/Invoice.php#L184) for more info.
